### ISSUE TITLE
Other payment methods unavailable

### ISSUE THREAD

**Issue by ebenoasis** [binemmanuel/flutter_paystack_max#2]
Which the package is greate, it has it's challenges. The other payment methods are not available. Only the Card option is showing even after other payment methods to the code
![Screenshot_1714774879](https://github.com/binemmanuel/flutter_paystack_max/assets/63258642/4dd299bf-8479-4d95-bdc2-885273053662)

**Comment by binemmanuel** [comment]
Can you provide a sample code so that I can re-create the error you are having?

**Comment by ebenoasis** [comment]
I just copied and pasted from the example you gave in the pub.dev
[This link](https://pub.dev/packages/flutter_paystack_max/example)

**Comment by binemmanuel** [comment]
Make sure to check all the options you want from your [preference](https://dashboard.paystack.com/#/settings/preferences)
