### ISSUE TITLE
PAYSTACK 

### ISSUE THREAD

**Issue by kelvinyashim** [binemmanuel/flutter_paystack_max#6]
After paying the modal then waits to show that another modal is loading then it shows connection timed out

**Comment by binemmanuel** [comment]
After paying I doubt if there is a loading modal from the example but if you can provide more details (sample code, screenshots) bout this issue, it'll be helpful.

**Comment by kelvinyashim** [comment]
Hi yes theirs no modal. That was a error on my part
However once the modal shows up on my debug console it says did not find
Frame lockedcanvas

**Comment by kelvinyashim** [comment]
Also when i cancel payment it still pays 
And how do i handle that 
this is what i have so far


 if (response.status) {
      await firestore.createOrder(order);
      cartProvider.clearCart();
      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(
        backgroundColor: Colors.green,
        content: Text('Payment successful!'),
      ));
    } else {
      ScaffoldMessenger.of(context).showSnackBar(SnackBar(
        backgroundColor: Colors.red,
        content: Text('Payment failed: ${response.message}'),
      ));
    }

**Comment by binemmanuel** [comment]
If you log/print the response you'll see that it returns 


```dart
{
  "status": true,
  "message": "Verification successful",
  "data": {
    "id": 4100527671,
    "domain": "test",
    "status": "abandoned",
    "reference": "ps_1724349127944175"
  }
}
```

or

```dart
{
  "status": true,
  "message": "Verification successful",
  "data": {
    "id": 4100526349,
    "domain": "test",
    "status": "success",
    "reference": "ps_1724349091658435"
  }
}
```

The point is that Paystack always returns true for `response.status` and you should keep an eye on `response.data.status` instead. So, if you update to check for the status like below then you'll be good.

```dart
if (response.data.status == PaystackTransactionStatus.success) {
  // Payment was successful
}
```

PaystackTransactionStatus is an enum that has the following values
1. PaystackTransactionStatus.reversed
2. PaystackTransactionStatus.failed
3. PaystackTransactionStatus.abandoned and
4. PaystackTransactionStatus.success

**Comment by kelvinyashim** [comment]
thank you
